name: CI

on:
  push:
  schedule:
    - cron: '0 1 * * *' # Test every day at 1AM
  
jobs:

  Full_Analysis:

    runs-on: ubuntu-latest
    container:
        image: rootproject/root:6.22.00-ubuntu20.04

    steps:

      - name: Hello world
        run: echo Hello world

      - name: Install git on container
        run: |
          apt update
          apt install -y git

      - name: Checkout repository
        #uses: actions/checkout@v2
        uses: actions/checkout@v3
        with:
          submodules: recursive

      #- name: Checkout submodules
        #run: | 
          #git submodule update --init --recursive

      - name: Compile
        run: | 
          pwd
          ls
          cd rooutil
          pwd
          ls
          echo Compile rooutil
          make -j
          echo DONE Compile rooutil
          cd ../analysis
          echo Compile analysis
          make -j
          echo DONE Compile Compile analysis

