name: CI

on:
  push:
  schedule:
    - cron: '0 1 * * *' # Test every day at 1AM
  
jobs:

  Full_Analysis:

    runs-on: ubuntu-latest
    container:
        image: rootproject/root:6.22.00-ubuntu20.04

    steps:

      - name: Hello world
        run: echo Hello world

      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      #- name: Checkout submodules
        #run: | 
          #git submodule update --init --recursive

      - name: Compile
        run: | 
          pwd
          ls
          cd rooutil
          pwd
          ls
          make -j
          cd ..
          make -j

