name: CI

on:
  push:
  schedule:
    - cron: '0 1 * * *' # Test every day at 1AM
  
jobs:

  Full_Analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
